#327 source in package
openlibraryenvironment/gokb pull request #334
Opened 2020-10-12 14:07 UTC by VolkerHBZ

2020-10-12 15:18 UTC, hornmo requested changes

2020-10-12 15:18 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/FTUpdateService.groovy
> +        result.tippPackageSource = kbc.pkg.source ? kbc.pkg.source : ""
Not sure if we need the package source on each single TIPP as well. Is there a specific use-case?

2020-10-12 15:18 UTC, hornmo commented on server/gokbg3/grails-app/domain/org/gokb/cred/Source.groovy
> +    frequency(nullable:true, blank:true, default: "d")
According to the UI spec this would have to be `1D`.

2020-10-12 15:18 UTC, hornmo commented on server/gokbg3/grails-app/domain/org/gokb/cred/Package.groovy
> +
Since Source information is a general KBComponent link, this information is already added at the start via `addCoreGOKbXmlFields`.

2020-10-12 15:18 UTC, hornmo commented on scripts/es_reset.sh
> +      },
Since we will generate the `name` of the Source directly from the Package name, we won't really need this field here. More useful would probably be to add the `frequency` instead.

2020-10-12 15:18 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/FTUpdateService.groovy
> +          result.source = [name : kbc.source.name, id:kbc.source.id]
Adjust according to requested index mapping changes (`frequency` instead of `name`)

2020-10-13 08:57 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/FTUpdateService.groovy
> +        result.tippPackageSource = kbc.pkg.source ? kbc.pkg.source : ""
no specific use case, just storing the source along with the package for later use by external entities, as this was demanded by the sentence:"Die Daten müssen entsprechend beim Package auch über die APIs ausgeliefert werden (OAI-PMH und ES)". Implementing it this way was my interpretation of that line.

I'll erase it. We can put it back, if needed.

2020-10-13 08:58 UTC, VolkerHBZ commented on server/gokbg3/grails-app/domain/org/gokb/cred/Source.groovy
> +    frequency(nullable:true, blank:true, default: "d")
ok.

2020-10-13 09:20 UTC, VolkerHBZ commented on server/gokbg3/grails-app/domain/org/gokb/cred/Package.groovy
> +
true. i didn't notice that before. thx.

2020-10-13 09:22 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/FTUpdateService.groovy
> +          result.source = [name : kbc.source.name, id:kbc.source.id]
done

2020-10-13 11:44 UTC, hornmo approved these changes

2020-10-13 11:44 UTC, merged