Tipp validierung #14
openlibraryenvironment/gokb pull request #410
Opened 2021-02-08 15:15 UTC by VolkerHBZ

moved validateDTO in the respective Domain classes
added some new media types

2021-02-10 12:15 UTC, hornmo requested changes
A consistent way to unify this properly would be to refer everything back to the index of the specific TIPP to basically bundle errors for the specific KBART line, and put everything in the same hierarchy as the input format. So `result.errors.tipps` would be an array like: 

```
[
    [
        index: 1456,
        errors: [
            title: [
                name: [
                    [message: "No title name", baddata: <tipp.title.name>],
                ],
                publishedFrom: [
                   [message: "Illegal date for publishedFrom", baddata: <tipp.title.publishedFrom>]
                ]
           ],
          url: [
               [message: "Illegal URL format", baddata: <tipp.url>]
           ]
      ]
  ],
]
```
So errors.tipps.size() would return the number of faulty KBART lines, and inside their `errors` object the structure would be the same as the one that came in.

2021-02-10 12:15 UTC, hornmo commented on server/gokbg3/grails-app/domain/org/gokb/cred/TitleInstance.groovy
> +    def valErrors = []
This does not conform to the current object error layout. `result.errors` of any validateDTO should be a Map with property names as keys (same as `messageService.processValidationErrors()`).

2021-02-10 12:15 UTC, hornmo commented on server/gokbg3/grails-app/domain/org/gokb/cred/TitleInstance.groovy
> +
Since the values are all created in Bootstrap, `RefdataCategory.lookup(<cat>, <value>)` would be better here.

2021-02-10 12:15 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +     "Biography", "Legal Text", "Cartography", "Miscellaneous", "Other"].each { med ->
List contains `Other` twice.

2021-02-10 13:42 UTC, VolkerHBZ commented on server/gokbg3/grails-app/domain/org/gokb/cred/TitleInstance.groovy
> +
nope, as there are also german keywords that need to be mapped to the same refdataValues.

2021-02-12 09:29 UTC, VolkerHBZ commented on server/gokbg3/grails-app/domain/org/gokb/cred/TitleInstance.groovy
> +    def valErrors = []
the error objects are adapted according to the suggested layout.

2021-02-15 14:20 UTC, hornmo approved these changes

2021-02-15 14:20 UTC, merged