Add new endpoint /api/elasticsearchTunnel/ (GOKbIT-32)
openlibraryenvironment/gokb pull request #415
Opened 2021-02-15 15:26 UTC by philboeselager

2021-02-16 09:41 UTC, hornmo requested changes

2021-02-16 09:41 UTC, hornmo commented on server/gokbg3/grails-app/conf/application.groovy
> +  [pattern: '/api/getApiTunnel',        access: ['permitAll']],
The pattern has to refer to the controller action name rather than the service method

2021-02-18 10:52 UTC, philboeselager commented on server/gokbg3/grails-app/conf/application.groovy
> +  [pattern: '/api/getApiTunnel',        access: ['permitAll']],
That's right. Change follows.

2021-02-18 11:13 UTC, hornmo approved these changes

2021-02-18 11:13 UTC, merged