Package comparison
openlibraryenvironment/gokb pull request #418
Opened 2021-02-16 17:59 UTC by hornmo

2021-02-17 08:07 UTC, VolkerHBZ commented on server/gokbg3/grails-app/controllers/org/gokb/PackagesController.groovy
> +    def sdf = new SimpleDateFormat("yyyy-MM-dd")
maybe use dateFormatterService!?

2021-02-17 08:13 UTC, VolkerHBZ requested changes

2021-02-17 08:13 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/PackageService.groovy
> +    def sdf = new SimpleDateFormat("yyyy-MM-dd")
dateFormatterService!?

2021-02-17 08:14 UTC, philboeselager approved these changes

2021-02-18 08:30 UTC, VolkerHBZ approved these changes

2021-02-18 10:06 UTC, merged