Touch component when changing historyEvent (ERMS-3221)
openlibraryenvironment/gokb pull request #426
Opened 2021-03-15 14:50 UTC by philboeselager

This is my first very simple approach.
Please feel free to indicate what I might be missing.

2021-03-15 15:45 UTC, hornmo commented
The property `lastUpdated` is reserved for auto-timestamps by GORM and cannot be manually set (see http://gorm.grails.org/6.1.x/hibernate/manual/#eventsAutoTimestamping). Alternatives would be `lastSeen` (as a `Long` ) or a descriptive `lastUpdatedComment` `String`.

2021-03-16 13:25 UTC, hornmo requested changes
See previous comment

2021-03-17 09:52 UTC, philboeselager commented
> The property `lastUpdated` is reserved for auto-timestamps by GORM and cannot be manually set (see http://gorm.grails.org/6.1.x/hibernate/manual/#eventsAutoTimestamping). Alternatives would be `lastSeen` (as a `Long` via `Date.getTime()` ) or a descriptive `lastUpdatedComment` `String`.

@hornmo I'm preferring `lastSeen` here, since changing `lastUpdatedComment` might conflict with other use cases of this field. Using `lastSeen` will lead to some unnecessary updates, right? But this should be OK, as we should be able to handle the overall number.

2021-03-18 13:18 UTC, hornmo requested changes

2021-03-18 13:18 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/FTUpdateService.groovy
> +          "OR (o.dateCreated > :ts) OR (o.lastSeen > :seen)) ", [ts: from, seen: seen], [readonly: true])[0]
Since the change in `lastSeen` triggers the auto timestamp and adjusts `lastUpdated`, the changes here are not necessary.

2021-03-18 13:18 UTC, hornmo commented on server/gokbg3/grails-app/domain/org/gokb/cred/ComponentHistoryEvent.groovy
> +  }
This might be a bit more complicated, since the event has to be created before its participants. This means we would probably only need the `afterUpdate` (since adding/removing a participant from `participants` should trigger an update) and should check if two participants exist before doing the touch.

2021-03-24 12:09 UTC, hornmo approved these changes

2021-03-24 12:09 UTC, merged