Kbart export 67
openlibraryenvironment/gokb pull request #437
Opened 2021-04-16 15:07 UTC by VolkerHBZ

new: coming in two flavours

2021-04-19 16:51 UTC, hornmo requested changes

2021-04-19 16:51 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/PackageService.groovy
> +    record.publisher_name = pick (tipp.publisherName, tipp.title?.getCurrentPublisher(), exportType)
Value for the title version should be the `name` of the Org (`getCurrentPublisher()?.name`)

2021-04-20 09:44 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/PackageService.groovy
> +    record.publisher_name = pick (tipp.publisherName, tipp.title?.getCurrentPublisher(), exportType)
done

2021-04-21 11:23 UTC, hornmo approved these changes

2021-04-21 11:23 UTC, merged