Tipp service 96
openlibraryenvironment/gokb pull request #440
Opened 2021-05-04 12:12 UTC by VolkerHBZ

2021-05-07 10:46 UTC, hornmo requested changes

2021-05-07 10:46 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +      ti.ids = tipp.ids
The new title has to be saved (and flushed) before doing anything with Combos.

2021-05-07 10:46 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +    if (ti) {
If we are doing this with matched titles as well as new titles we may overwrite existing title info here, which is not necessarily desired. Restricting this to new titles for now seems better. We may want to work with ReviewRequests for changed title data instead.

2021-05-07 10:46 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +
Since we will have a publisherName in the TIPP, we should also try to set this on the title as well (via titleLookupService.addPublisher)

2021-05-07 11:30 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +    if (ti) {
I supposed that copying the way the IntegrationController works, by using the ComponentpdateService methods, it'd give a similarly desired result including the ReviewRequests and won't puzzle eventual users using the new mechanism more than before.

2021-05-07 11:31 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +
maybe implementing a copy constructor in TitleInstance and it's subclasses?

2021-06-24 11:32 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +    if (ti) {
done: if the title is found in the database, it's not changed except for being linked to the tipp.

2021-07-07 12:15 UTC, hornmo requested changes

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/controllers/org/gokb/IntegrationController.groovy
> +        def title_class_name = TitleInstance.determineTitleClass(titleObj.publitionType?:titleObj.type)
`publitionType` -> `publicationType`

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/controllers/org/gokb/IntegrationController.groovy
> +              result.message = messageService.resolveCode('crossRef.title.success', [title], locale)
Message parameter should be `title.name`

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/controllers/org/gokb/PublicController.groovy
> +                            sanitize( tipp.title?.getPrecedingTitleId() ) + '\t' +
We should fallback to TIPP info if no title info is available.

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/domain/org/gokb/cred/TitleInstancePackagePlatform.groovy
> +  }
Why not just do `RefdataCategory.lookup(TitleInstancePackagePlatform.RD_PUBLICATION_TYPE, someType)`? No need to iterate manually then.

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/FTUpdateService.groovy
> +        result.updater = 'org'
Remove, duplicate lines to 106

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +  }
We can get around looking up every TIPP by default by specifying the conditions (combo to package, no title combo) in an hql and only getting a list of IDs of affected TIPPs.

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +      titleLookupService.addPublisher(tipp.publisherName, ti)
New component has to be saved before adding Combos. Also this is called in line 78 again, so this may be removed.

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +          found.matches as JSON,
Since `matches` returned from TitleLookupService currently contains full components in `object`, these have to be explicitly mapped to JSON. Existing ReviewRequests hold all other linked components as maps in an array `additionalInfo.otherComponents` of the form `[oid: <obj.logEntityId>, name: <obj.name>]`.

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +          found.conflicts as JSON,
See above

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/src/main/groovy/org/gokb/UpdatePkgTippsRun.groovy
> +      dummy = pkg.nominalPlatform
Unused?

2021-07-07 12:15 UTC, hornmo commented on server/gokbg3/src/main/groovy/org/gokb/UpdatePkgTippsRun.groovy
> +          hostPlatformUuid : tippJson.hostPlatform.uuid,
Use `pkg` & `platform` as query params for `find()`, as documented at https://github.com/openlibraryenvironment/gokb/wiki/Elasticsearch-API (component-specific fields).

2021-07-07 13:29 UTC, VolkerHBZ commented on server/gokbg3/grails-app/controllers/org/gokb/IntegrationController.groovy
> +        def title_class_name = TitleInstance.determineTitleClass(titleObj.publitionType?:titleObj.type)
done

2021-07-07 13:35 UTC, VolkerHBZ commented on server/gokbg3/grails-app/controllers/org/gokb/IntegrationController.groovy
> +              result.message = messageService.resolveCode('crossRef.title.success', [title], locale)
ok

2021-07-07 13:35 UTC, VolkerHBZ commented on server/gokbg3/grails-app/controllers/org/gokb/PublicController.groovy
> +                            sanitize( tipp.title?.getPrecedingTitleId() ) + '\t' +
ok

2021-07-07 13:41 UTC, VolkerHBZ commented on server/gokbg3/grails-app/domain/org/gokb/cred/TitleInstancePackagePlatform.groovy
> +  }
This was implemented to circumvent problems with case-sensitive matching (in the rdv_cache)

I'll try your suggestion.

2021-07-07 13:43 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/FTUpdateService.groovy
> +        result.updater = 'org'
ok.

2021-07-07 13:49 UTC, VolkerHBZ commented on server/gokbg3/src/main/groovy/org/gokb/UpdatePkgTippsRun.groovy
> +      dummy = pkg.nominalPlatform
deleted

2021-07-09 12:02 UTC, VolkerHBZ commented on server/gokbg3/grails-app/domain/org/gokb/cred/TitleInstancePackagePlatform.groovy
> +  }
works

2021-07-09 12:35 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +          found.matches as JSON,
Mapping the matched components to that format

2021-07-13 16:16 UTC, hornmo approved these changes

2021-07-13 16:17 UTC, merged