Add CuratoryGroup argument to all calls of ReviewRequestService.raise() (GOKbIT-143)
openlibraryenvironment/gokb pull request #463
Opened 2021-08-26 11:32 UTC by philboeselager

2021-08-27 10:31 UTC, hornmo approved these changes

2021-09-01 08:36 UTC, hornmo requested changes

2021-09-01 08:36 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/ComponentLookupService.groovy
> +    if (component.curatoryGroups?.size() == 1){
TitleInstances for example don't have the Combo property `curatoryGroups`, therfore this throws a MissingPropertyException. The best way to check is `KBComponent.has(object, 'curatoryGroups')`.

2021-09-01 11:32 UTC, philboeselager commented
Tests:

- ignored: 3
- passed: 100

2021-09-01 11:49 UTC, hornmo approved these changes

2021-09-01 11:49 UTC, merged