Coverage matching 112
openlibraryenvironment/gokb pull request #464
Opened 2021-08-27 12:39 UTC by VolkerHBZ

2021-09-02 18:01 UTC, hornmo requested changes

2021-09-02 18:01 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +            && (today.isAfter(it.startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate())))
This will fail if startDate is null, so we have to filter for that.

2021-09-02 18:01 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +          if (journal.publishedFrom == latest.startDate && journal.publishedTo == latest.endDate) {
We have to compare the ranges here instead, so something like `startDate >= publishedFrom && endDate <= publishedTo`, complicated a bit since each of the values is optional.

2021-09-02 18:01 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +      def pubTo = tipp.accessEndDate ? GOKbTextUtils.completeDateString(tipp.accessEndDate.format("yyyy-MM-dd"), false) : null
We cannot derive the pubFrom / pubTo from access dates. If anything we could check a coverageStatement for `startVolume 1 && startDate`, but even that sounds a bit shaky. Better to leave this to the ZDB Augment job.

2021-09-02 18:01 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +      title_changed |= ti.hasProperty('publishedTo') ? ClassUtils.updateDateField(pubTo, ti, 'publishedTo') : false
See above.

2021-09-03 11:35 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +            && (today.isAfter(it.startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate())))
changed

2021-09-03 11:36 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +          if (journal.publishedFrom == latest.startDate && journal.publishedTo == latest.endDate) {
adapted it

2021-09-03 11:36 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +      def pubTo = tipp.accessEndDate ? GOKbTextUtils.completeDateString(tipp.accessEndDate.format("yyyy-MM-dd"), false) : null
deleted

2021-09-03 11:36 UTC, VolkerHBZ commented on server/gokbg3/grails-app/services/org/gokb/TippService.groovy
> +      title_changed |= ti.hasProperty('publishedTo') ? ClassUtils.updateDateField(pubTo, ti, 'publishedTo') : false
dito

2021-09-07 08:41 UTC, hornmo approved these changes

2021-09-07 08:41 UTC, merged