139 ezb enrichment
openlibraryenvironment/gokb pull request #473
Opened 2022-01-06 11:43 UTC by philboeselager

2022-01-18 17:46 UTC, hornmo reviewed
This raises some questions we have to discuss, mainly if we even want to create ReviewRequests for EZB conflicts.

The changes in TippService seem out of place and don't really make sense to me.

2022-02-15 13:16 UTC, hornmo requested changes
The changes in `TippService` are overhauled and should be removed from this PR.

2022-02-15 13:16 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TitleAugmentService.groovy
> +        CuratoryGroup.findByNameIlike(grailsApplication.config.gokb.ezbAugment.rrCurators) : null
if augment is activated via config, we should probably create the `CuratoryGroup` here if it doesn't exist.

2022-02-15 13:16 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +        AugmentJob.schedule(grailsApplication.config.gokb.augment.cron)
This does not seem to work right now, and I cannot find the corresponding method.

2022-02-15 13:16 UTC, hornmo commented on server/gokbg3/grails-app/services/org/gokb/TitleAugmentService.groovy
> +    if ((!titleInstance.hasProperty('publishedFrom') || !titleInstance.publishedFrom) && info.publishedFrom) {
The property is defined in the generic base class `TitleInstance`, therefore this check shouldn't be necessary.

2022-03-14 08:27 UTC, philboeselager reviewed
can't be approved by the raiser of the PR. Feel dree, @hornmo :-)

2022-03-14 16:00 UTC, hornmo approved these changes

2022-03-14 16:01 UTC, merged