151 elasticsearch upgrade 7.15.1
openlibraryenvironment/gokb pull request #501
Opened 2022-04-26 10:46 UTC by philboeselager

2022-04-26 11:48 UTC, hornmo requested changes

2022-04-26 11:48 UTC, hornmo commented on server/gokbg3/grails-app/services/com/k_int/ESSearchService.groovy
> +          searchResponse = esClient.search(searchRequest, RequestOptions.DEFAULT)
esClient is not defined.

2022-04-28 10:03 UTC, philboeselager commented on server/gokbg3/grails-app/services/com/k_int/ESSearchService.groovy
> +          searchResponse = esClient.search(searchRequest, RequestOptions.DEFAULT)
Sorry. Fixed.

2022-05-03 09:39 UTC, hornmo requested changes
Looks fine functionally, but we should go for ES 7.10.2 for now.

2022-05-05 16:55 UTC, hornmo approved these changes

2022-05-06 10:05 UTC, merged