334 cleanup global identifiers
openlibraryenvironment/gokb pull request #531
Opened 2022-12-05 16:40 UTC by philboeselager

2022-12-05 17:17 UTC, hornmo requested changes

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                targetType: targetTypeTitle,
More specifically 'Book'

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                targetType: targetTypeTitle,
More specifically 'Book'

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                targetType: targetTypeTitle,
More specifically 'Journal'

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                targetType: targetTypeTitle,
More specifically 'Journal'

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                targetType: targetTypeTitle,
More specifically 'Journal'

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                targetType: targetTypeTitle,
More specifically 'Journal'

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                targetType: targetTypeOrg,
In our case it is used for type 'Package'.

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +            ],
Although it might be useful in other cases, for us targetType = 'Org' would be correct.

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +            ],
Although it might be useful in other cases, for us targetType = 'Org' would be correct.

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +            ],
Although it might be useful in other cases, for us targetType = 'Org' would be correct.

2022-12-05 17:17 UTC, hornmo commented on server/gokbg3/grails-app/init/gokbg3/BootStrap.groovy
> +                baseUrl: "https://www.wikidata.org/wiki/"
Although it might be useful in other cases, for us targetType = 'Org' would be correct.

2022-12-05 17:17 UTC, hornmo commented on scripts/clean_identifier_URLs.sql
> +SELECT * FROM identifier WHERE id_value LIKE '%d-nb.info/gnd%';
To be extra safe, specifying the namespace in the where clause would be great.

2022-12-07 11:03 UTC, philboeselager commented
@hornmo : Should be ready to be excuted on servers now.

Procedure:

1.  Run commands from clean_identifier_URLs.sql.
2.  Run admin function "Expunge Rejected Components"
3.  Deploy (with this Bootstrap)
4.  Run commands from transform_global_identifiers.sql.

2022-12-08 11:18 UTC, hornmo commented on scripts/clean_identifier_URLs.sql
> +  AND idns.idns_value = 'global';
The rdv_id can be derived via:
```
SET edit_status_id = (
   SELECT rdv_id 
   FROM refdata_value 
   WHERE rdv_value = 'Rejected' 
   AND rdv_owner = (
       SELECT rdc_id 
       FROM refdata_category 
       WHERE rdc_label = 'KBComponent.EditStatus'
    )
) 
```

2022-12-08 17:13 UTC, hornmo approved these changes

2022-12-08 17:30 UTC, merged